### ISSUE TITLE
W+1 feature is not generated

### ISSUE THREAD

**Issue by bratao** [hiroshi-manabe/CRFSegmenter#2]
Hello @hiroshi-manabe ,

In a previous conversation you noticed that the W+1 feature was not generated. I also noticed when playing with the code.

> Let's assume the sentence is "Alice was beginning to get very tired of sitting by her sister on the bank" and the word we are trying to tag is "get". "--wordw" determines the range from which the software generates the feature functions. If "--wordw" is 2, the range is from "beggining" (current position - 2) ... "very" (current position + 2 - 1). (I'm not sure why I decided to -1, but it is so for now.) "--wordn" determines the maximum word cluster length: For example, if "--wordw" is 2 and "--wordn" is also 2, the generated word clusters are "W-2/beggining_to", "W-1/to", "W-1/to_get", "W+0/get" and "W+0/get_very". Note that "W-2/beggining" and "W+1/very" are not generated. The rationale is that a non-adjacent word is seldom useful when inferring the label. (I noticed it is not the case with "W+1/very", which is an adjacent word of "get". I will try fixing it along with the range of "--wordw".)

**Comment by hiroshi-manabe** [comment]
Hello @bratao,

I refactored the code in the `refactor` branch and fixed the W+1 feature problem there.

Now the tagger and high-order CRF engine core are separate and you can see the generated feature templates!

I'm going to update the README, make the current `master` obsolete, etc., but for the time being, you can try the `refactor` branch.

Your feedback is highly appreciated!

**Comment by bratao** [comment]
@hiroshi-manabe , that is awesome !!!! 
I'm very excited to use. It seems that the Tagger folder is not compiled anymore, and your commit mention about being integrated in DataConverter. Could give an example of usage ??

**Comment by hiroshi-manabe** [comment]
Let's assume the input is like:

```
Time[TAB]NN
flies[TAB]VBZ
like[TAB]IN
an[TAB]DT
arrow[TAB]NN
.[TAB].

```

(There must be an empty line at the end of each sequence)

First, pass the input to DataConverter.

```
$ cat input.txt | DataConverter/DataConverter --tag [--dict dict.txt] > features.txt
```

The output will be in the following format:

```
<word>[TAB]<possible labels>[TAB]<correct label>[TAB]<feature template 1>[TAB]<feature template 2>...
...
```

<possible labels> are comma-separated labels and are fetched from the dictionary. If the word is not found in the dictionary, <possible labels> will be "*" (any label).

<feature template> is in the format `<label length>:<feature tag>`. <feature tag> is just any unique string, like "W+0/TIME".

So, the output will be like:

```
Time[TAB]NN,VB[TAB]NN[TAB]1:W+0/Time[TAB]...
flies[TAB]NNS,VBZ[TAB]VBZ[TAB]1:W+0/files[TAB]...
...
```

Then pass this output to HighOrderCRF.

When training, like:

```
$ HighOrderCRF/HighOrderCRF --train features.txt --model model.file --regtype L1 --coeff 0.05
```

(The parameters are the ones I use for my application)

When tagging, like:

```
$ cat features.txt | HighOrderCRF/HighOrderCRF --tag --model model.file
```

The output will be:

```
<word>[TAB]<inferred label>
...
```

Note that the first column (<word>) is not actually used either in training models or inferring labels. It's passed through only for convenience.
