### ISSUE TITLE
Elastic net regularization (L1 + L2)

### ISSUE THREAD

**Issue by bratao** [hiroshi-manabe/CRFSegmenter#3]
Hello,
Thank you again for this project, the refactoring is working very good here =)

In crfsuite and Wapiti I get the best results with a L1 + L2 regularization ( 0.1 and 0.1 for my dataset).

With CRFSegmenter, I can only set one or another. It is possible to use both ?

**Comment by hiroshi-manabe** [comment]
Hello,
Glad to hear the refactoring is working fine :)

> In crfsuite and Wapiti I get the best results with a L1 + L2 regularization ( 0.1 and 0.1 for my dataset).

First of all, regularization is not my forte and I wrote that part of code without really understanding it.

I mistakenly thought L1 and L2 regularization cannot be used together, but I knew from your comment that it is not the case.

It may take some time, but I am going to implement that correctly.

**Comment by bratao** [comment]
Great,
I read T he crfsuite code and I guess that the necessary chances are very minor.
In optimizer evaluate, callback:

if (!useL1Optimization) should not be a boolean, it must be a float representing the L2 regularization.

**Comment by hiroshi-manabe** [comment]
Thank you for the advice!
I hope my changes solve your problem.
