### ISSUE TITLE
Much worse performance for 1-order Tagger comparard to CRFSuite

### ISSUE THREAD

**Issue by bratao** [hiroshi-manabe/CRFSegmenter#5]
Hi @hiroshi-manabe , sorry to bother you again.

I was evaluating replacing CRFSuite for a project that use it  as a Sequential Labeler. 

I created the input for both project, with only one feature ( the token) to evaluate and compare the performance. The used input files are attached.

[input.zip](https://github.com/hiroshi-manabe/CRFSegmenter/files/709993/input.zip)

For CRFSegmenter I used the command to train:
`
HighOrderCRFMain.exe --train input.txt --c1 0.1 --c2 0.1 --model crfsegmenter.model`

And to test:
`HighOrderCRFMain.exe --test input.txt --model crfsegmenter.model`

See that I´m testing with the **same file that I used to train**.

The results are very bad:

```
Performance by label (#match, #model, #ref) (precision, recall, F1):
    O: (144, 170, 144) (0.8471, 1.0000, 0.9172)
    I-numero_processo: (13, 13, 180) (1.0000, 0.0722, 0.1347)
    B-tipo: (6, 8, 23) (0.7500, 0.2609, 0.3871)
    I-envolvido: (376, 471, 485) (0.7983, 0.7753, 0.7866)
    I-tipo: (12, 12, 73) (1.0000, 0.1644, 0.2824)
    B-advogado: (116, 116, 118) (1.0000, 0.9831, 0.9915)
    B-numero_processo: (74, 74, 74) (1.0000, 1.0000, 1.0000)
    I-advogado: (1535, 1812, 1631) (0.8471, 0.9411, 0.8917)
    B-envolvido: (46, 55, 148) (0.8364, 0.3108, 0.4532)
    B-movimentacao: (67, 72, 74) (0.9306, 0.9054, 0.9178)
    I-movimentacao: (7686, 8068, 7864) (0.9527, 0.9774, 0.9649)
    B-secao: (0, 0, 4) (0.0000, 0.0000, 0.0000)
    I-texto_categoria: (30, 33, 68) (0.9091, 0.4412, 0.5941)
    I-secao: (12, 16, 34) (0.7500, 0.3529, 0.4800)
    B-texto_categoria: (4, 4, 4) (1.0000, 1.0000, 1.0000)

Item accuracy: 10121 / 10924 (0.9265)
Instance Accuracy: 0 / 1 (0.0000)
```
With CRFsuite I get a near perfect result.

`crfsuite.exe learn -p c1=0.1 -p c2=0.1 -m crfsuite.model input_crfsuite.txt`

`crfsuite.exe tag -t -m crfsuite.model input_crfsuite.txt`

```
Performance by label (#match, #model, #ref) (precision, recall, F1):
    B-tipo: (20, 20, 23) (1.0000, 0.8696, 0.9302)
    I-tipo: (73, 73, 73) (1.0000, 1.0000, 1.0000)
    B-numero_processo: (74, 74, 74) (1.0000, 1.0000, 1.0000)
    I-numero_processo: (180, 180, 180) (1.0000, 1.0000, 1.0000)
    O: (144, 145, 144) (0.9931, 1.0000, 0.9965)
    B-envolvido: (148, 149, 148) (0.9933, 1.0000, 0.9966)
    I-envolvido: (483, 483, 485) (1.0000, 0.9959, 0.9979)
    B-advogado: (118, 118, 118) (1.0000, 1.0000, 1.0000)
    I-advogado: (1631, 1631, 1631) (1.0000, 1.0000, 1.0000)
    B-movimentacao: (74, 74, 74) (1.0000, 1.0000, 1.0000)
    I-movimentacao: (7864, 7867, 7864) (0.9996, 1.0000, 0.9998)
    B-secao: (4, 4, 4) (1.0000, 1.0000, 1.0000)
    I-secao: (34, 34, 34) (1.0000, 1.0000, 1.0000)
    B-texto_categoria: (4, 4, 4) (1.0000, 1.0000, 1.0000)
    I-texto_categoria: (68, 68, 68) (1.0000, 1.0000, 1.0000)
Macro-average precision, recall, F1: (0.999067, 0.991029, 0.994743)
Item accuracy: 10919 / 10924 (0.9995)
Instance accuracy: 0 / 1 (0.0000)
```

Did I did something wrong? The input file for CRFSegmenter is with a wrong format?( I did not used other features, including features with high-order to make a fair comparison)

Thank you again!

**Comment by hiroshi-manabe** [comment]
CRFsuite generates implicit transition features, but CRFSegmenter doesn't.
So, you will have to add "transition features" - i.e. features with two labels - explicitly.
I think adding "2:*" feature template to each line will do the trick.

**Comment by bratao** [comment]
That was it. Thank you!
